version: '2'

services:
    reverseproxy:
        image: niazzaki/reverseproxy
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    wnode:
        depends_on:
            - reverseproxy
        image: niazzaki/wnodeapp
        restart: always
      
    fnode:
        depends_on:
            - reverseproxy
        image: niazzaki/fnodeapp
        restart: always
 
